### 1. Importing the Libraries:

Using Opendatasets Library:

In [3]:
# pip install opendatasets

import opendatasets as od
import pandas as pd

kaggle_dataset="https://www.kaggle.com/datasets/shilongzhuang/telecom-customer-churn-by-maven-analytics"
od.download(kaggle_dataset)

Skipping, found downloaded files in ".\telecom-customer-churn-by-maven-analytics" (use force=True to force download)

### 2. Read the dataset:

In [4]:
churndata = pd.read_csv('./telecom-customer-churn-by-maven-analytics/telecom_customer_churn.csv')

### 3. Explore the dataset:

In [5]:
churndata.shape

(7043, 38)

In [6]:
churndata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 38 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   object
 1   Gender                             7043 non-null   object
 2   Age                                7043 non-null   int64
 3   Married                            7043 non-null   object
 4   Number of Dependents               7043 non-null   int64
 5   City                               7043 non-null   object
 6   Zip Code                           7043 non-null   int64
 7   Latitude                           7043 non-null   float64
 8   Longitude                          7043 non-null   float64
 9   Number of Referrals                7043 non-null   int64
 10  Tenure in Months                   7043 non-null   int64
 11  Offer                              7043 non-null   object
 12  Phone Service                      7043 non-null   object
 13  Avg Monthly Long Distance Charges  6361 non-null   float64
 14  Multiple Lines                     6361 non-null   object
 15  Internet Service                   7043 non-null   object
 16  Internet Type                      5517 non-null   object
 17  Avg Monthly GB Download            5517 non-null   float64
 18  Online Security                    5517 non-null   object
 19  Online Backup                      5517 non-null   object
 20  Device Protection Plan             5517 non-null   object
 21  Premium Tech Support               5517 non-null   object
 22  Streaming TV                       5517 non-null   object
 23  Streaming Movies                   5517 non-null   object
 24  Streaming Music                    5517 non-null   object
 25  Unlimited Data                     5517 non-null   object
 26  Contract                           7043 non-null   object
 27  Paperless Billing                  7043 non-null   object
 28  Payment Method                     7043 non-null   object
 29  Monthly Charge                     7043 non-null   float64
 30  Total Charges                      7043 non-null   float64
 31  Total Refunds                      7043 non-null   float64
 32  Total Extra Data Charges           7043 non-null   int64
 33  Total Long Distance Charges        7043 non-null   float64
 34  Total Revenue                      7043 non-null   float64
 35  Customer Status                    7043 non-null   object
 36  Churn Category                     1869 non-null   object
 37  Churn Reason                       1869 non-null   object
dtypes: float64(9), int64(6), object(23)
memory usage: 2.0+ MB

In [7]:
churndata.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [8]:
churndata.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

#### 3.a. Find null/ missing values

In [9]:
missing = pd.concat([churndata.isnull().sum(), 100 * churndata.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count',ascending=False)

                                   count          %
Churn Reason                        5174  73.463013
Churn Category                      5174  73.463013
Internet Type                       1526  21.666903
Unlimited Data                      1526  21.666903
Streaming Music                     1526  21.666903
Streaming Movies                    1526  21.666903
Streaming TV                        1526  21.666903
Premium Tech Support                1526  21.666903
Device Protection Plan              1526  21.666903
Online Security                     1526  21.666903
Avg Monthly GB Download             1526  21.666903
Online Backup                       1526  21.666903
Multiple Lines                       682   9.683374
Avg Monthly Long Distance Charges    682   9.683374
Phone Service                          0   0.000000
Contract                               0   0.000000
Age                                    0   0.000000
Customer Status                        0   0.000000
Total Revenue                          0   0.000000
Total Long Distance Charges            0   0.000000
Total Extra Data Charges               0   0.000000
Total Refunds                          0   0.000000
Total Charges                          0   0.000000
Monthly Charge                         0   0.000000
Payment Method                         0   0.000000
Paperless Billing                      0   0.000000
Married                                0   0.000000
Number of Dependents                   0   0.000000
City                                   0   0.000000
Zip Code                               0   0.000000
Latitude                               0   0.000000
Longitude                              0   0.000000
Gender                                 0   0.000000
Number of Referrals                    0   0.000000
Tenure in Months                       0   0.000000
Offer                                  0   0.000000
Internet Service                       0   0.000000
Customer ID                            0   0.000000

#### 3.b Exploring the Categorical Features:

In [10]:
churndata.select_dtypes('object').T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
Customer ID,0002-ORFBO,0003-MKNFE,0004-TLHLJ,0011-IGKFF,0013-EXCHZ,0013-MHZWF,0013-SMEOE,0014-BMAQU,0015-UOCOJ,0016-QLJIS,...,9975-SKRNR,9978-HYCIN,9979-RGMZT,9985-MWVIX,9986-BONCE,9987-LUTYD,9992-RRAMN,9992-UJOEL,9993-LHIEB,9995-HOTOH
Gender,Female,Male,Male,Male,Female,Female,Female,Male,Female,Female,...,Male,Male,Female,Female,Female,Female,Male,Male,Male,Male
Married,Yes,No,No,Yes,Yes,No,Yes,Yes,No,Yes,...,No,Yes,No,No,No,No,Yes,No,Yes,Yes
City,Frazier Park,Glendale,Costa Mesa,Martinez,Camarillo,Midpines,Lompoc,Napa,Simi Valley,Sheridan,...,Sierraville,Bakersfield,Los Angeles,Hume,Fallbrook,La Mesa,Riverbank,Elk,Solana Beach,Sierra City
Offer,None,None,Offer E,Offer D,None,Offer E,Offer A,Offer B,Offer E,None,...,Offer E,None,Offer E,Offer E,None,Offer D,Offer D,Offer E,Offer A,None
Phone Service,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No
Multiple Lines,No,Yes,No,No,No,No,No,Yes,No,Yes,...,No,No,No,No,No,No,Yes,No,No,NaN
Internet Service,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes
Internet Type,Cable,Cable,Fiber Optic,Fiber Optic,Fiber Optic,Cable,Fiber Optic,Fiber Optic,DSL,Cable,...,NaN,Fiber Optic,Fiber Optic,Fiber Optic,NaN,DSL,Fiber Optic,DSL,Cable,Cable
Online Security,No,No,No,No,No,No,Yes,Yes,Yes,Yes,...,NaN,No,No,No,NaN,Yes,No,No,Yes,Yes
Online Backup,Yes,No,No,Yes,No,No,Yes,No,No,Yes,...,NaN,Yes,Yes,No,NaN,No,No,Yes,No,Yes
Device Protection Plan,No,No,Yes,Yes,No,No,Yes,No,No,Yes,...,NaN,No,No,No,NaN,No,No,No,Yes,Yes
Premium Tech Support,Yes,No,No,No,Yes,Yes,Yes,Yes,No,Yes,...,NaN,No,No,No,NaN,Yes,No,No,Yes,No
Streaming TV,Yes,No,No,Yes,Yes,Yes,Yes,No,No,Yes,...,NaN,Yes,Yes,No,NaN,No,No,No,No,Yes
Streaming Movies,No,Yes,No,Yes,No,Yes,Yes,No,No,Yes,...,NaN,No,Yes,No,NaN,No,Yes,No,Yes,Yes
Streaming Music,No,Yes,No,No,No,Yes,Yes,No,No,Yes,...,NaN,No,Yes,No,NaN,Yes,Yes,No,Yes,Yes
Unlimited Data,Yes,No,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,...,NaN,No,Yes,Yes,NaN,Yes,Yes,Yes,Yes,Yes
Contract,One Year,Month-to-Month,Month-to-Month,Month-to-Month,Month-to-Month,Month-to-Month,Two Year,Two Year,Two Year,Two Year,...,Month-to-Month,One Year,One Year,Month-to-Month,Month-to-Month,One Year,Month-to-Month,Month-to-Month,Two Year,Two Year
Paperless Billing,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,No,Yes,Yes,Yes,No,No,Yes,Yes,No,No
Payment Method,Credit Card,Credit Card,Bank Withdrawal,Bank Withdrawal,Credit Card,Credit Card,Bank Withdrawal,Credit Card,Bank Withdrawal,Credit Card,...,Credit Card,Bank Withdrawal,Credit Card,Credit Card,Bank Withdrawal,Credit Card,Bank Withdrawal,Credit Card,Credit Card,Bank Withdrawal
Customer Status,Stayed,Stayed,Churned,Churned,Churned,Stayed,Stayed,Stayed,Stayed,Stayed,...,Joined,Stayed,Stayed,Churned,Churned,Stayed,Churned,Joined,Stayed,Stayed
Churn Category,NaN,NaN,Competitor,Dissatisfaction,Dissatisfaction,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Competitor,Competitor,NaN,Dissatisfaction,NaN,NaN,NaN
Churn Reason,NaN,NaN,Competitor had better devices,Product dissatisfaction,Network reliability,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Competitor had better devices,Competitor made better offer,NaN,Product dissatisfaction,NaN,NaN,NaN

In [11]:
churndata['Customer Status'].unique()

array(['Stayed', 'Churned', 'Joined'], dtype=object)

In [36]:
churncategory = pd.DataFrame(churndata['Churn Category'].unique())
churncategory.columns = ['Category of Reason for Leaving']
churncategory.sort_values('Category of Reason for Leaving')

  Category of Reason for Leaving
5                       Attitude
1                     Competitor
2                Dissatisfaction
3                          Other
4                          Price
0                            NaN

In [34]:
churnreason = pd.DataFrame(churndata['Churn Reason'].unique())
churnreason.columns = ['Specific Reason for Leaving']
churnreason.sort_values('Specific Reason for Leaving')

                  Specific Reason for Leaving
8                Attitude of service provider
9                  Attitude of support person
1               Competitor had better devices
5                Competitor made better offer
10  Competitor offered higher download speeds
11               Competitor offered more data
13                                   Deceased
6                                  Don't know
19                         Extra data charges
12   Lack of affordable download/upload speed
17            Lack of self-service on Website
4                   Limited range of services
7                       Long distance charges
14                                      Moved
3                         Network reliability
18           Poor expertise of online support
20            Poor expertise of phone support
16                             Price too high
2                     Product dissatisfaction
15                    Service dissatisfaction
0                                         NaN

#### 3.c. Exploring the Numerical Features:

In [37]:
churndata.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,7043.0,46.509726,16.750352,19.000000,32.000000,46.000000,60.000000,80.000000
Number of Dependents,7043.0,0.468692,0.962802,0.000000,0.000000,0.000000,0.000000,9.000000
Zip Code,7043.0,93486.070567,1856.767505,90001.000000,92101.000000,93518.000000,95329.000000,96150.000000
Latitude,7043.0,36.197455,2.468929,32.555828,33.990646,36.205465,38.161321,41.962127
Longitude,7043.0,-119.756684,2.154425,-124.301372,-121.788090,-119.595293,-117.969795,-114.192901
Number of Referrals,7043.0,1.951867,3.001199,0.000000,0.000000,0.000000,3.000000,11.000000
Tenure in Months,7043.0,32.386767,24.542061,1.000000,9.000000,29.000000,55.000000,72.000000
Avg Monthly Long Distance Charges,6361.0,25.420517,14.200374,1.010000,13.050000,25.690000,37.680000,49.990000
Avg Monthly GB Download,5517.0,26.189958,19.586585,2.000000,13.000000,21.000000,30.000000,85.000000
Monthly Charge,7043.0,63.596131,31.204743,-10.000000,30.400000,70.050000,89.750000,118.750000
Total Charges,7043.0,2280.381264,2266.220462,18.800000,400.150000,1394.550000,3786.600000,8684.800000
Total Refunds,7043.0,1.962182,7.902614,0.000000,0.000000,0.000000,0.000000,49.790000
Total Extra Data Charges,7043.0,6.860713,25.104978,0.000000,0.000000,0.000000,0.000000,150.000000
Total Long Distance Charges,7043.0,749.099262,846.660055,0.000000,70.545000,401.440000,1191.100000,3564.720000
Total Revenue,7043.0,3034.379056,2865.204542,21.360000,605.610000,2108.640000,4801.145000,11979.340000